import os
from typing import Dict, Any
from app.database.supabase import get_supabase_client
from services.llm import call_llm
from app.pipeline.state import AgentState

ORCHESTRATOR_SYSTEM_PROMPT = """
You are the Orchestrator Agent for the AI Venture Studio.
Your role is to consume the structured analysis plan generated by the Planning Agent, and coordinate the specialized analyses.

Given the Plan, output:
1. Coordination Summary: A brief assessment of the next analysis nodes.
2. Downstream Directives: Clear instructions for Strategy, Finance, Marketing, and Risk specialized agents based on the plan.
3. Execution Status: Set status to "Ready for Specialized Analysis".

Be concise, clear, and structured.
"""

def orchestrator_agent_node(state: AgentState) -> Dict[str, Any]:
    """
    Orchestrator Agent Node logic.
    Consumes the plan, coordinates tasks, and updates the shared pipeline state.
    Logs execution logs to Supabase database.
    """
    project_id = state.get("project_id")
    plan = state.get("plan", "")
    
    print(f"--- [Orchestrator Agent Node] Starting execution for Project {project_id} ---")
    
    # 1. Prompt LLM using the plan as user input
    orchestration_result = call_llm(prompt=plan, system_prompt=ORCHESTRATOR_SYSTEM_PROMPT, preferred_provider="nvidia")
    
    # 2. Log transaction to Supabase agent_logs
    try:
        supabase = get_supabase_client()
        supabase.table("agent_logs").insert({
            "project_id": project_id,
            "agent_name": "Orchestrator Agent",
            "status": "completed",
            "input_data": {
                "plan_preview": plan[:500] if plan else ""
            },
            "output_data": {
                "orchestration": orchestration_result[:1000]
            }
        }).execute()
        print("Logged Orchestrator Agent execution to Supabase.")
    except Exception as db_err:
        print(f"Supabase Agent Log Sync Warning (continuing): {str(db_err)}")
        
    print(f"--- [Orchestrator Agent Node] Finished execution ---")
    return {
        "research_results": orchestration_result
    }
