import io
from typing import Dict, Any, List, Optional
from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from pptx import Presentation
from pptx.util import Inches as PptxInches, Pt as PptxPt
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

def format_title(text: str) -> str:
    return text.replace("_", " ").title()

def generate_docx(
    report_type: str,
    content: Dict[str, Any],
    project_name: str,
    section_labels: Optional[Dict[str, str]] = None
) -> io.BytesIO:
    """Generates a styled Word document from report contents.
    
    Args:
        section_labels: Optional mapping of field_key -> human-readable heading.
                        Comes from the report registry's export_mapping.
    """
    doc = Document()
    
    # Document Title / Cover Header
    title = doc.add_paragraph()
    title_run = title.add_run(f"{project_name} - {report_type}")
    title_run.font.size = Pt(24)
    title_run.font.bold = True
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    doc.add_paragraph("Generated by AI Venture Studio Deliberation Pipeline").alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_paragraph().add_run("_" * 60).bold = True
    
    # Sections Loop
    for section_name, section_content in content.items():
        heading = (section_labels or {}).get(section_name, format_title(section_name))
        doc.add_heading(heading, level=1)
        
        if isinstance(section_content, list):
            for bullet in section_content:
                doc.add_paragraph(str(bullet), style='List Bullet')
        else:
            doc.add_paragraph(str(section_content))
        doc.add_paragraph()  # Spacing
        
    doc_io = io.BytesIO()
    doc.save(doc_io)
    doc_io.seek(0)
    return doc_io

def generate_pptx(
    report_type: str,
    content: Dict[str, Any],
    project_name: str,
    section_labels: Optional[Dict[str, str]] = None
) -> io.BytesIO:
    """Generates a professional PowerPoint presentation deck from report contents."""
    prs = Presentation()
    
    # Slide 1: Cover Slide
    slide_layout = prs.slide_layouts[0]  # Title slide layout
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    
    title.text = f"{project_name}\n{report_type}"
    subtitle.text = "AI Venture Studio Boardroom Blueprint"
    
    # Slides for each section
    content_layout = prs.slide_layouts[5]  # Blank layout with title
    for section_name, section_content in content.items():
        slide = prs.slides.add_slide(content_layout)
        heading = (section_labels or {}).get(section_name, format_title(section_name))
        slide.shapes.title.text = heading
        
        # Add textbox for text content
        left   = PptxInches(1)
        top    = PptxInches(2)
        width  = PptxInches(8)
        height = PptxInches(4.5)
        
        tx_box = slide.shapes.add_textbox(left, top, width, height)
        tf = tx_box.text_frame
        tf.word_wrap = True
        
        if isinstance(section_content, list):
            for idx, bullet in enumerate(section_content):
                p = tf.add_paragraph() if idx > 0 else tf.paragraphs[0]
                p.text = f"\u2022 {bullet}"
                p.font.size = PptxPt(16)
        else:
            p = tf.paragraphs[0]
            text_str = str(section_content)
            p.text = text_str[:570] + "..." if len(text_str) > 600 else text_str
            p.font.size = PptxPt(16)
            
    ppt_io = io.BytesIO()
    prs.save(ppt_io)
    ppt_io.seek(0)
    return ppt_io

def generate_pdf(
    report_type: str,
    content: Dict[str, Any],
    project_name: str,
    section_labels: Optional[Dict[str, str]] = None
) -> io.BytesIO:
    """Generates a highly-styled PDF document from report contents using reportlab."""
    pdf_io = io.BytesIO()
    doc = SimpleDocTemplate(
        pdf_io,
        pagesize=letter,
        rightMargin=54,
        leftMargin=54,
        topMargin=54,
        bottomMargin=54
    )
    
    styles = getSampleStyleSheet()
    
    # Custom Premium styles
    title_style = ParagraphStyle(
        'CoverTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=24,
        leading=28,
        textColor=colors.HexColor('#6366F1'),
        alignment=1,  # Center
        spaceAfter=15
    )
    
    subtitle_style = ParagraphStyle(
        'CoverSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica-Oblique',
        fontSize=10,
        leading=12,
        textColor=colors.HexColor('#6B7280'),
        alignment=1,
        spaceAfter=30
    )
    
    h1_style = ParagraphStyle(
        'SectionHeader',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=16,
        leading=20,
        textColor=colors.HexColor('#1E1B4B'),
        spaceBefore=15,
        spaceAfter=10,
        keepWithNext=True
    )
    
    body_style = ParagraphStyle(
        'SectionBody',
        parent=styles['BodyText'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#374151'),
        spaceAfter=12
    )
    
    bullet_style = ParagraphStyle(
        'SectionBullet',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#374151'),
        leftIndent=15,
        firstLineIndent=-10,
        spaceAfter=6
    )
    
    story = []
    
    # Title & Metadata Cover section
    story.append(Spacer(1, 40))
    story.append(Paragraph(f"{project_name} - {report_type}", title_style))
    story.append(Paragraph("Generated by AI Venture Studio Deliberation Pipeline", subtitle_style))
    story.append(Spacer(1, 20))
    story.append(Paragraph("<font color='#E5E7EB'>__________________________________________________________________</font>", body_style))
    story.append(Spacer(1, 20))
    
    # Render sections
    for section_name, section_content in content.items():
        heading = (section_labels or {}).get(section_name, format_title(section_name))
        story.append(Paragraph(heading, h1_style))
        
        if isinstance(section_content, list):
            for bullet in section_content:
                story.append(Paragraph(f"\u2022 {bullet}", bullet_style))
        else:
            story.append(Paragraph(str(section_content), body_style))
            
        story.append(Spacer(1, 10))
        
    doc.build(story)
    pdf_io.seek(0)
    return pdf_io
